Use template strings for Slack message payload
GitbookIO/services-slack pull request #5
Opened 2017-01-11 14:48 UTC by yangshun

Some of the Slack messages posted have a little bit of inconsistency and extra quotation marks:

<img width="521" alt="screen shot 2017-01-11 at 10 47 07 pm" src="https://cloud.githubusercontent.com/assets/1315101/21852909/e874a510-d84f-11e6-9adb-eda230ae9609.png">

This PR converts them to template strings which is more readable. A node 6 upgrade is required also (presuming Heroku is being used for hosting).

2017-01-11 14:58 UTC, AaronO requested changes
Looks good as a whole, but you changed the extraction of the "payload" variable which might break things.

2017-01-11 14:58 UTC, AaronO commented on index.js
> +    var payload = req.body;
Is there a reason why you changed this variable ?

2017-01-11 15:06 UTC, yangshun commented on index.js
> +    var payload = req.body;
I'm not sure why `req.body.payload` works in the first place. Seems that `res.body` is the POST payload according to this: https://github.com/expressjs/body-parser#bodyparserjsonoptions.

My `body-parser` version is `1.14.1`.

2017-01-11 15:13 UTC, AaronO commented on index.js
> +    var payload = req.body;
@yangshun Yep, `.payload` is an attribute of JSON delivered by the webhook, which looks like:

```json
{
    "eventName": "...",
    "payload": {
        ...
        "book": "org/book_id",
        ...
    }
}
```

2017-01-11 15:16 UTC, yangshun commented on index.js
> +    var payload = req.body;
Ah I understand now. I was mistaken; I used this payload when testing locally.

```
{
  "book": { ... },
  "comment": { ... },
  "thread": { ... },
  "action": "opened"
}
```

Thanks for clarifying!

2017-01-11 15:17 UTC, yangshun commented on index.js
> +    var payload = req.body;
Have fixed!

2017-01-17 18:06 UTC, yangshun commented
Hi @AaronO I have fixed the `payload` issue. Could you have a look at this again?

2017-01-21 07:19 UTC, yangshun commented
I have deployed my own version on Heroku and tested it. It works fine 👌

2017-09-27 08:56 UTC, closed without merging